# Form implementation generated from reading ui file 'c:\Users\Angel Rodriguez\Microsoft\ProyectoKWESTE\Front\ventanasui\V_CodigosCuentasBalanzaComprobacion.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Formulario_BusquedaCuetasCodigos_BalanzaComprobacion(object):
    def setupUi(self, Formulario_BusquedaCuetasCodigos_BalanzaComprobacion):
        Formulario_BusquedaCuetasCodigos_BalanzaComprobacion.setObjectName("Formulario_BusquedaCuetasCodigos_BalanzaComprobacion")
        Formulario_BusquedaCuetasCodigos_BalanzaComprobacion.resize(650, 460)
        Formulario_BusquedaCuetasCodigos_BalanzaComprobacion.setMinimumSize(QtCore.QSize(650, 460))
        Formulario_BusquedaCuetasCodigos_BalanzaComprobacion.setMaximumSize(QtCore.QSize(650, 460))
        Formulario_BusquedaCuetasCodigos_BalanzaComprobacion.setStyleSheet("#Formulario_BusquedaCuetasCodigos_BalanzaComprobacion{\n"
"background-color: rgb(234, 234, 234);\n"
"}\n"
"[objectName*=\"contenedor\"]{\n"
"background-color: rgb(234, 234, 234);\n"
"}\n"
"[objectName*=\"btn_btn\"]{\n"
"background-color: rgb(64, 150, 216);\n"
"font-size:14px;\n"
"font-weight:bold;\n"
"font-family:\"Arial\";\n"
"border: none;\n"
"min-height: 25px;\n"
"padding: 0px 4px;\n"
"border-radius: 2px;\n"
"color:rgb(255, 255, 255)\n"
"}\n"
"[objectName*=\"btn_btn\"]:pressed{\n"
"background-color: rgb(56, 134, 193);\n"
"}\n"
"#btn_btn_Eliminar:hover{\n"
"background-color: rgb(227, 71, 71);\n"
"}\n"
"#btn_btn_Eliminar:pressed{\n"
"background-color: rgb(212, 0, 0);\n"
"}\n"
"[objectName*=\"txt\"]{\n"
"border: none;\n"
"border-bottom: 1px solid rgb(0, 0, 0);\n"
"border-radius: 2px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"[objectName*=\"txt\"]:hover{\n"
"border-bottom: 2px solid rgb(5, 95, 212);\n"
"}\n"
"[objectName*=\"txt\"]:focus{\n"
"border-bottom: 2px solid rgb(5, 95, 212);\n"
"}\n"
"[objectName*=\"etiquetaSub\"]{\n"
"font-size:13px;\n"
"font-weight:bold;\n"
"font-family:\"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"[objectName*=\"etiqueta_\"]{\n"
"font-size:12px;\n"
"font-weight:bold;\n"
"font-family:\"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"[objectName^=\"Tabla\"]{\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(29, 28, 28);\n"
"}\n"
"[objectName*=\"Tabla\"]:QHeaderView{\n"
"background-color: #4CAF50;\n"
"border: 1px solid #ddd;\n"
"color: white;\n"
"font-weight: bold;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Formulario_BusquedaCuetasCodigos_BalanzaComprobacion)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.contenedor = QtWidgets.QFrame(parent=Formulario_BusquedaCuetasCodigos_BalanzaComprobacion)
        self.contenedor.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.contenedor.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.contenedor.setObjectName("contenedor")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.contenedor)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.contenedor_2 = QtWidgets.QFrame(parent=self.contenedor)
        self.contenedor_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.contenedor_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.contenedor_2.setObjectName("contenedor_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.contenedor_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.etiquetaSub_filtros = QtWidgets.QLabel(parent=self.contenedor_2)
        self.etiquetaSub_filtros.setObjectName("etiquetaSub_filtros")
        self.gridLayout_3.addWidget(self.etiquetaSub_filtros, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.etiqueta_buscarpor = QtWidgets.QLabel(parent=self.contenedor_2)
        self.etiqueta_buscarpor.setObjectName("etiqueta_buscarpor")
        self.gridLayout_2.addWidget(self.etiqueta_buscarpor, 0, 0, 1, 1)
        self.cajaopciones_busca_cuenta_codigo = QtWidgets.QComboBox(parent=self.contenedor_2)
        self.cajaopciones_busca_cuenta_codigo.setObjectName("cajaopciones_busca_cuenta_codigo")
        self.cajaopciones_busca_cuenta_codigo.addItem("")
        self.cajaopciones_busca_cuenta_codigo.addItem("")
        self.gridLayout_2.addWidget(self.cajaopciones_busca_cuenta_codigo, 0, 1, 1, 1)
        self.txt_filtro = QtWidgets.QLineEdit(parent=self.contenedor_2)
        self.txt_filtro.setObjectName("txt_filtro")
        self.gridLayout_2.addWidget(self.txt_filtro, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.contenedor_2)
        self.contenedor_3 = QtWidgets.QFrame(parent=self.contenedor)
        self.contenedor_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.contenedor_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.contenedor_3.setObjectName("contenedor_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.contenedor_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.etiquetaSub_Campos = QtWidgets.QLabel(parent=self.contenedor_3)
        self.etiquetaSub_Campos.setObjectName("etiquetaSub_Campos")
        self.gridLayout_4.addWidget(self.etiquetaSub_Campos, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.etiqueta_numcuenta = QtWidgets.QLabel(parent=self.contenedor_3)
        self.etiqueta_numcuenta.setObjectName("etiqueta_numcuenta")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.etiqueta_numcuenta)
        self.txt_numcuenta = QtWidgets.QLineEdit(parent=self.contenedor_3)
        self.txt_numcuenta.setObjectName("txt_numcuenta")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txt_numcuenta)
        self.etiqueta_codigo = QtWidgets.QLabel(parent=self.contenedor_3)
        self.etiqueta_codigo.setObjectName("etiqueta_codigo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.etiqueta_codigo)
        self.txt_codigo = QtWidgets.QLineEdit(parent=self.contenedor_3)
        self.txt_codigo.setObjectName("txt_codigo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txt_codigo)
        self.gridLayout_4.addLayout(self.formLayout, 1, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_btn_Guadar = QtWidgets.QPushButton(parent=self.contenedor_3)
        self.btn_btn_Guadar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_btn_Guadar.setObjectName("btn_btn_Guadar")
        self.horizontalLayout.addWidget(self.btn_btn_Guadar)
        self.btn_btn_Actualizar = QtWidgets.QPushButton(parent=self.contenedor_3)
        self.btn_btn_Actualizar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_btn_Actualizar.setObjectName("btn_btn_Actualizar")
        self.horizontalLayout.addWidget(self.btn_btn_Actualizar)
        self.btn_btn_Eliminar = QtWidgets.QPushButton(parent=self.contenedor_3)
        self.btn_btn_Eliminar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_btn_Eliminar.setObjectName("btn_btn_Eliminar")
        self.horizontalLayout.addWidget(self.btn_btn_Eliminar)
        self.btn_btn_CargarExcel = QtWidgets.QPushButton(parent=self.contenedor_3)
        self.btn_btn_CargarExcel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_btn_CargarExcel.setObjectName("btn_btn_CargarExcel")
        self.horizontalLayout.addWidget(self.btn_btn_CargarExcel)
        self.gridLayout_4.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.contenedor_3)
        self.contenedor_4 = QtWidgets.QFrame(parent=self.contenedor)
        self.contenedor_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.contenedor_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.contenedor_4.setObjectName("contenedor_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.contenedor_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.etiquetaSub_Tabla_DatosExistentes = QtWidgets.QLabel(parent=self.contenedor_4)
        self.etiquetaSub_Tabla_DatosExistentes.setObjectName("etiquetaSub_Tabla_DatosExistentes")
        self.verticalLayout.addWidget(self.etiquetaSub_Tabla_DatosExistentes)
        self.Tabla_DatosExistentes = QtWidgets.QTableView(parent=self.contenedor_4)
        self.Tabla_DatosExistentes.setObjectName("Tabla_DatosExistentes")
        self.verticalLayout.addWidget(self.Tabla_DatosExistentes)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.etiquetaSub_Tabla_DatosNuevos = QtWidgets.QLabel(parent=self.contenedor_4)
        self.etiquetaSub_Tabla_DatosNuevos.setObjectName("etiquetaSub_Tabla_DatosNuevos")
        self.verticalLayout_2.addWidget(self.etiquetaSub_Tabla_DatosNuevos)
        self.Tabla_DatosNuevos = QtWidgets.QTableView(parent=self.contenedor_4)
        self.Tabla_DatosNuevos.setObjectName("Tabla_DatosNuevos")
        self.verticalLayout_2.addWidget(self.Tabla_DatosNuevos)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addWidget(self.contenedor_4)
        self.gridLayout.addWidget(self.contenedor, 0, 0, 1, 1)

        self.retranslateUi(Formulario_BusquedaCuetasCodigos_BalanzaComprobacion)
        QtCore.QMetaObject.connectSlotsByName(Formulario_BusquedaCuetasCodigos_BalanzaComprobacion)

    def retranslateUi(self, Formulario_BusquedaCuetasCodigos_BalanzaComprobacion):
        _translate = QtCore.QCoreApplication.translate
        Formulario_BusquedaCuetasCodigos_BalanzaComprobacion.setWindowTitle(_translate("Formulario_BusquedaCuetasCodigos_BalanzaComprobacion", "Form"))
        self.etiquetaSub_filtros.setText(_translate("Formulario_BusquedaCuetasCodigos_BalanzaComprobacion", "Filtros de Busqueda"))
        self.etiqueta_buscarpor.setText(_translate("Formulario_BusquedaCuetasCodigos_BalanzaComprobacion", "Buscar por"))
        self.cajaopciones_busca_cuenta_codigo.setItemText(0, _translate("Formulario_BusquedaCuetasCodigos_BalanzaComprobacion", "Núm. Cuenta"))
        self.cajaopciones_busca_cuenta_codigo.setItemText(1, _translate("Formulario_BusquedaCuetasCodigos_BalanzaComprobacion", "Código"))
        self.etiquetaSub_Campos.setText(_translate("Formulario_BusquedaCuetasCodigos_BalanzaComprobacion", "Campos"))
        self.etiqueta_numcuenta.setText(_translate("Formulario_BusquedaCuetasCodigos_BalanzaComprobacion", "Número de Cuenta:"))
        self.etiqueta_codigo.setText(_translate("Formulario_BusquedaCuetasCodigos_BalanzaComprobacion", "Código:"))
        self.btn_btn_Guadar.setText(_translate("Formulario_BusquedaCuetasCodigos_BalanzaComprobacion", "Agregar"))
        self.btn_btn_Actualizar.setText(_translate("Formulario_BusquedaCuetasCodigos_BalanzaComprobacion", "Actualizar"))
        self.btn_btn_Eliminar.setText(_translate("Formulario_BusquedaCuetasCodigos_BalanzaComprobacion", "Eliminar"))
        self.btn_btn_CargarExcel.setText(_translate("Formulario_BusquedaCuetasCodigos_BalanzaComprobacion", "Cargar CSV"))
        self.etiquetaSub_Tabla_DatosExistentes.setText(_translate("Formulario_BusquedaCuetasCodigos_BalanzaComprobacion", "Cuentas Almacenadas"))
        self.etiquetaSub_Tabla_DatosNuevos.setText(_translate("Formulario_BusquedaCuetasCodigos_BalanzaComprobacion", "Datos por Almacenar"))
