# Form implementation generated from reading ui file 'ventana_rutas.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ventana_configuracion_rutasdocumentos(object):
    def setupUi(self, ventana_configuracion_rutasdocumentos):
        ventana_configuracion_rutasdocumentos.setObjectName("ventana_configuracion_rutasdocumentos")
        ventana_configuracion_rutasdocumentos.resize(500, 350)
        ventana_configuracion_rutasdocumentos.setMinimumSize(QtCore.QSize(500, 0))
        ventana_configuracion_rutasdocumentos.setMaximumSize(QtCore.QSize(500, 350))
        ventana_configuracion_rutasdocumentos.setStyleSheet("[objectName^=\"lbt_title\"] {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    margin-bottom: 5px; \n"
"    margin-top: 5px;\n"
"    margin-left: 0px;\n"
"}\n"
"[objectName^=\"lbl\"] {\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    margin-bottom: 5px; \n"
"    margin-top: 5px;\n"
"    margin-left: 0px;\n"
"}\n"
"[objectName^=\"txt\"] {\n"
"    font-size: 12px;\n"
"    font-family: Arial;\n"
"    border-bottom: 1px solid;\n"
"    border-top: 0px;\n"
"}\n"
"[objectName^=\"rb_rb\"] {\n"
"    font-size: 14px;\n"
"    font-family: Arial;\n"
"}\n"
"#btn_btn_aceptar{\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    min-height: 30px;\n"
"    min-width: 70px;\n"
"    border-radius: 4px;\n"
"    background-color: rgb(33, 195, 47);\n"
"}\n"
"#btn_btn_aceptar:hover{\n"
"background-color: rgb(76, 175, 80);\n"
"}\n"
"#txt_extension_documento{\n"
"margin-left:10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=ventana_configuracion_rutasdocumentos)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.panel_cuerpo_ventana = QtWidgets.QWidget(parent=self.centralwidget)
        self.panel_cuerpo_ventana.setObjectName("panel_cuerpo_ventana")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.panel_cuerpo_ventana)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbt_title_rutasreportes = QtWidgets.QLabel(parent=self.panel_cuerpo_ventana)
        self.lbt_title_rutasreportes.setObjectName("lbt_title_rutasreportes")
        self.verticalLayout.addWidget(self.lbt_title_rutasreportes)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_ruta = QtWidgets.QLabel(parent=self.panel_cuerpo_ventana)
        self.lbl_ruta.setObjectName("lbl_ruta")
        self.gridLayout.addWidget(self.lbl_ruta, 1, 0, 1, 1)
        self.lbl_nombre = QtWidgets.QLabel(parent=self.panel_cuerpo_ventana)
        self.lbl_nombre.setObjectName("lbl_nombre")
        self.gridLayout.addWidget(self.lbl_nombre, 0, 0, 1, 1)
        self.txt_nombre = QtWidgets.QLineEdit(parent=self.panel_cuerpo_ventana)
        self.txt_nombre.setObjectName("txt_nombre")
        self.gridLayout.addWidget(self.txt_nombre, 0, 1, 1, 1)
        self.panel_acciones = QtWidgets.QWidget(parent=self.panel_cuerpo_ventana)
        self.panel_acciones.setMinimumSize(QtCore.QSize(0, 0))
        self.panel_acciones.setObjectName("panel_acciones")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.panel_acciones)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rb_rb_ingresar = QtWidgets.QRadioButton(parent=self.panel_acciones)
        self.rb_rb_ingresar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.rb_rb_ingresar.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.rb_rb_ingresar.setObjectName("rb_rb_ingresar")
        self.horizontalLayout_3.addWidget(self.rb_rb_ingresar)
        self.rb_rb_eliminar = QtWidgets.QRadioButton(parent=self.panel_acciones)
        self.rb_rb_eliminar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.rb_rb_eliminar.setAutoFillBackground(False)
        self.rb_rb_eliminar.setObjectName("rb_rb_eliminar")
        self.horizontalLayout_3.addWidget(self.rb_rb_eliminar)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout.addWidget(self.panel_acciones, 2, 0, 1, 2)
        self.txt_extension_documento = QtWidgets.QLineEdit(parent=self.panel_cuerpo_ventana)
        self.txt_extension_documento.setEnabled(False)
        self.txt_extension_documento.setMinimumSize(QtCore.QSize(60, 0))
        self.txt_extension_documento.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.txt_extension_documento.setFont(font)
        self.txt_extension_documento.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txt_extension_documento.setObjectName("txt_extension_documento")
        self.gridLayout.addWidget(self.txt_extension_documento, 0, 2, 1, 1)
        self.txt_ruta = QtWidgets.QLineEdit(parent=self.panel_cuerpo_ventana)
        self.txt_ruta.setObjectName("txt_ruta")
        self.gridLayout.addWidget(self.txt_ruta, 1, 1, 1, 2)
        self.labelId = QtWidgets.QLabel(parent=self.panel_cuerpo_ventana)
        self.labelId.setEnabled(False)
        self.labelId.setText("")
        self.labelId.setObjectName("labelId")
        self.gridLayout.addWidget(self.labelId, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.panel_tabla_rutas = QtWidgets.QWidget(parent=self.panel_cuerpo_ventana)
        self.panel_tabla_rutas.setObjectName("panel_tabla_rutas")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.panel_tabla_rutas)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabla_rutas = QtWidgets.QTableWidget(parent=self.panel_tabla_rutas)
        self.tabla_rutas.setObjectName("tabla_rutas")
        self.tabla_rutas.setColumnCount(2)
        self.tabla_rutas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_rutas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_rutas.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_2.addWidget(self.tabla_rutas)
        self.verticalLayout.addWidget(self.panel_tabla_rutas)
        self.verticalLayout_2.addWidget(self.panel_cuerpo_ventana)
        self.panel_inferior = QtWidgets.QWidget(parent=self.centralwidget)
        self.panel_inferior.setObjectName("panel_inferior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.panel_inferior)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_btn_aceptar = QtWidgets.QPushButton(parent=self.panel_inferior)
        self.btn_btn_aceptar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_btn_aceptar.setObjectName("btn_btn_aceptar")
        self.horizontalLayout.addWidget(self.btn_btn_aceptar)
        self.verticalLayout_2.addWidget(self.panel_inferior)
        ventana_configuracion_rutasdocumentos.setCentralWidget(self.centralwidget)

        self.retranslateUi(ventana_configuracion_rutasdocumentos)
        QtCore.QMetaObject.connectSlotsByName(ventana_configuracion_rutasdocumentos)
        ventana_configuracion_rutasdocumentos.setTabOrder(self.txt_nombre, self.txt_ruta)
        ventana_configuracion_rutasdocumentos.setTabOrder(self.txt_ruta, self.rb_rb_ingresar)
        ventana_configuracion_rutasdocumentos.setTabOrder(self.rb_rb_ingresar, self.rb_rb_eliminar)
        ventana_configuracion_rutasdocumentos.setTabOrder(self.rb_rb_eliminar, self.tabla_rutas)
        ventana_configuracion_rutasdocumentos.setTabOrder(self.tabla_rutas, self.btn_btn_aceptar)

    def retranslateUi(self, ventana_configuracion_rutasdocumentos):
        _translate = QtCore.QCoreApplication.translate
        ventana_configuracion_rutasdocumentos.setWindowTitle(_translate("ventana_configuracion_rutasdocumentos", "MainWindow"))
        self.lbt_title_rutasreportes.setText(_translate("ventana_configuracion_rutasdocumentos", "Rutas para los reportes"))
        self.lbl_ruta.setText(_translate("ventana_configuracion_rutasdocumentos", "Ruta relativa:"))
        self.lbl_nombre.setText(_translate("ventana_configuracion_rutasdocumentos", "Abreviación del repote:"))
        self.txt_nombre.setPlaceholderText(_translate("ventana_configuracion_rutasdocumentos", "Abreviación mas extensión del documento (doc.xlsx)"))
        self.rb_rb_ingresar.setText(_translate("ventana_configuracion_rutasdocumentos", "Ingresar"))
        self.rb_rb_eliminar.setText(_translate("ventana_configuracion_rutasdocumentos", "Eliminar"))
        self.txt_extension_documento.setText(_translate("ventana_configuracion_rutasdocumentos", ".xlsx"))
        self.txt_ruta.setPlaceholderText(_translate("ventana_configuracion_rutasdocumentos", "C:/..."))
        item = self.tabla_rutas.horizontalHeaderItem(0)
        item.setText(_translate("ventana_configuracion_rutasdocumentos", "Nombre"))
        item = self.tabla_rutas.horizontalHeaderItem(1)
        item.setText(_translate("ventana_configuracion_rutasdocumentos", "Ruta"))
        self.btn_btn_aceptar.setText(_translate("ventana_configuracion_rutasdocumentos", "Aceptar"))
