# Form implementation generated from reading ui file 'c:\Users\OEM\Documents\KENWORT_DEL_ESTE\programakw\App\Front\fecha.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(200, 100)
        Form.setMinimumSize(QtCore.QSize(200, 100))
        Form.setMaximumSize(QtCore.QSize(200, 16777215))
        Form.setStyleSheet("#w_principal{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.w_principal = QtWidgets.QWidget(parent=Form)
        self.w_principal.setObjectName("w_principal")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.w_principal)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.date_edit_date_movement = QtWidgets.QDateEdit(parent=self.w_principal)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setItalic(True)
        self.date_edit_date_movement.setFont(font)
        self.date_edit_date_movement.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.date_edit_date_movement.setReadOnly(False)
        self.date_edit_date_movement.setCalendarPopup(True)
        self.date_edit_date_movement.setDate(QtCore.QDate(2023, 1, 1))
        self.date_edit_date_movement.setObjectName("date_edit_date_movement")
        self.verticalLayout_2.addWidget(self.date_edit_date_movement)
        self.verticalLayout.addWidget(self.w_principal)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
