# Form implementation generated from reading ui file 'c:\Users\Angel Rodriguez\LUIS_ANGEL_VALLEJO\programakw\App\Front\ventanasui\inicio_sesion.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class UI_Inicio_Sesion(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(590, 289)
        Form.setStyleSheet("#w_login{\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"\n"
"#btn_aceptar_ingreso{\n"
"    background-color: rgb(76, 175, 80);\n"
"    border-radius: 12px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#btn_aceptar_ingreso:hover{\n"
"    background-color: rgb(0, 194, 12);\n"
"}\n"
"*[objectName *=\"btn_manejoventana\"]{\n"
"    background-color: transparent;\n"
"}\n"
"*[objectName *=\"txt\"]{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.w_login = QtWidgets.QWidget(parent=self.widget)
        self.w_login.setGeometry(QtCore.QRect(290, 60, 231, 161))
        self.w_login.setMinimumSize(QtCore.QSize(230, 0))
        self.w_login.setStyleSheet("#w_login{\n"
"background-color: qconicalgradient(cx:1, cy:0, angle:113.6, stop:0.0397727 rgba(237, 237, 237, 255), stop:0.585227 rgba(117, 117, 117, 255));\n"
"    box-shadow: 5px 5px 50px rgba(0, 0, 0, 20);\n"
"}")
        self.w_login.setObjectName("w_login")
        self.label = QtWidgets.QLabel(parent=self.w_login)
        self.label.setGeometry(QtCore.QRect(30, 15, 171, 23))
        font = QtGui.QFont()
        font.setFamily("Albertus Extra Bold")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.txt_usuario = QtWidgets.QLineEdit(parent=self.w_login)
        self.txt_usuario.setGeometry(QtCore.QRect(20, 50, 191, 25))
        font = QtGui.QFont()
        font.setFamily("Albertus Extra Bold")
        font.setPointSize(8)
        self.txt_usuario.setFont(font)
        self.txt_usuario.setStyleSheet("")
        self.txt_usuario.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txt_usuario.setObjectName("txt_usuario")
        self.txt_usuarioPassword = QtWidgets.QLineEdit(parent=self.w_login)
        self.txt_usuarioPassword.setGeometry(QtCore.QRect(20, 90, 191, 25))
        font = QtGui.QFont()
        font.setFamily("Albertus Extra Bold")
        font.setPointSize(8)
        self.txt_usuarioPassword.setFont(font)
        self.txt_usuarioPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_usuarioPassword.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txt_usuarioPassword.setObjectName("txt_usuarioPassword")
        self.btn_aceptar_ingreso = QtWidgets.QPushButton(parent=self.w_login)
        self.btn_aceptar_ingreso.setGeometry(QtCore.QRect(40, 124, 141, 31))
        self.btn_aceptar_ingreso.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("Albertus Medium")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_aceptar_ingreso.setFont(font)
        self.btn_aceptar_ingreso.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_aceptar_ingreso.setObjectName("btn_aceptar_ingreso")
        self.w_panelderecho_login = QtWidgets.QWidget(parent=self.widget)
        self.w_panelderecho_login.setGeometry(QtCore.QRect(50, 20, 241, 241))
        self.w_panelderecho_login.setStyleSheet("QWidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:25px;\n"
"}")
        self.w_panelderecho_login.setObjectName("w_panelderecho_login")
        self.label_2 = QtWidgets.QLabel(parent=self.w_panelderecho_login)
        self.label_2.setGeometry(QtCore.QRect(26, 80, 191, 91))
        self.label_2.setStyleSheet("QLabel{\n"
"    border-radius: 0px;\n"
"    border-image: url(:/imgs/LOGO_KREI.png);\n"
"        box-shadow: 5px 5px 50px rgba(0, 0, 0, 20);\n"
"}")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.btn_manejoventana_2 = QtWidgets.QPushButton(parent=self.w_panelderecho_login)
        self.btn_manejoventana_2.setGeometry(QtCore.QRect(210, 10, 21, 21))
        self.btn_manejoventana_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_manejoventana_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Icon_Close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_manejoventana_2.setIcon(icon)
        self.btn_manejoventana_2.setIconSize(QtCore.QSize(25, 25))
        self.btn_manejoventana_2.setObjectName("btn_manejoventana_2")
        self.btn_manejoventana = QtWidgets.QPushButton(parent=self.w_panelderecho_login)
        self.btn_manejoventana.setGeometry(QtCore.QRect(187, 10, 21, 21))
        self.btn_manejoventana.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_manejoventana.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Icon_Minimize.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_manejoventana.setIcon(icon1)
        self.btn_manejoventana.setIconSize(QtCore.QSize(25, 25))
        self.btn_manejoventana.setObjectName("btn_manejoventana")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Inicio de Sesión"))
        self.txt_usuario.setPlaceholderText(_translate("Form", "Usuario"))
        self.txt_usuarioPassword.setPlaceholderText(_translate("Form", "Contraseña"))
        self.btn_aceptar_ingreso.setText(_translate("Form", "Aceptar"))
