# Form implementation generated from reading ui file 'c:\Users\OEM\Documents\KENWORT_DEL_ESTE\programakw\App\Front\KWESTE.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ContenedorGeneralKWESTE(object):
    def setupUi(self, ContenedorGeneralKWESTE):
        ContenedorGeneralKWESTE.setObjectName("ContenedorGeneralKWESTE")
        ContenedorGeneralKWESTE.resize(950, 661)
        ContenedorGeneralKWESTE.setMinimumSize(QtCore.QSize(950, 650))
        ContenedorGeneralKWESTE.setMaximumSize(QtCore.QSize(950, 661))
        ContenedorGeneralKWESTE.setStyleSheet("#ContenedorGeneralKWESTE{\n"
"background-color: qconicalgradient(cx:0, cy:0, angle:114.5, stop:0.352273 rgba(0, 0, 0, 171), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"#l_logoKWESTE{\n"
"\n"
"}\n"
"#btnMinimizar{\n"
"border:none;\n"
"background: transparent;\n"
"}\n"
"#btnCerrar{\n"
"border:none;\n"
"background: transparent;\n"
"}\n"
"#table_porRealizarKWESTE{\n"
"background-color: rgb(231, 231, 231);\n"
"border-radius:12px;\n"
"}\n"
"#table_realizadoKWESTE{\n"
"background-color: rgb(231, 231, 231);\n"
"border-radius:12px;\n"
"}\n"
"#btnSubir{\n"
"background-color: qlineargradient(spread:pad, x1:0.113227, y1:0.426, x2:0, y2:0, stop:0 rgba(0, 255, 0, 153), stop:1 rgba(0, 0, 0, 63));\n"
"border-radius:12px;\n"
"}\n"
"#btnSubir::Hover{\n"
"background-color: rgb(46, 212, 60);\n"
"}\n"
"#btnEliminar{\n"
"background-color: qlineargradient(spread:pad, x1:0.113227, y1:0.426, x2:0, y2:0, stop:0 rgba(255, 0, 0, 153), stop:1 rgba(0, 0, 0, 63));\n"
"border-radius:12px;\n"
"}\n"
"#btnEliminar::Hover{\n"
"background-color: rgb(193, 15, 15);\n"
"}\n"
"#btnProcesar{\n"
"background-color: qlineargradient(spread:pad, x1:0.17, y1:0.7385, x2:0, y2:0, stop:0.431818 rgba(0, 245, 255, 142), stop:1 rgba(0, 0, 0, 97));\n"
"border-radius:12px;\n"
"}\n"
"#btnProcesar::Hover{\n"
"background-color: rgb(79, 188, 204);\n"
"}\n"
"#btnAyuda{\n"
"background-color: qconicalgradient(cx:1, cy:1, angle:286.1, stop:0 rgba(0, 0, 0, 153), stop:1 rgba(255, 255, 118, 255));\n"
"border-radius:8px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(ContenedorGeneralKWESTE)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.gridLayout.setContentsMargins(5, 0, 5, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(parent=ContenedorGeneralKWESTE)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 550))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 550))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_4 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.l_titulo_reportes_cola = QtWidgets.QLabel(parent=self.widget_4)
        self.l_titulo_reportes_cola.setMinimumSize(QtCore.QSize(0, 23))
        self.l_titulo_reportes_cola.setMaximumSize(QtCore.QSize(16777215, 23))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.l_titulo_reportes_cola.setFont(font)
        self.l_titulo_reportes_cola.setScaledContents(True)
        self.l_titulo_reportes_cola.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.l_titulo_reportes_cola.setObjectName("l_titulo_reportes_cola")
        self.verticalLayout.addWidget(self.l_titulo_reportes_cola)
        self.table_porRealizarKWESTE = QtWidgets.QTableWidget(parent=self.widget_4)
        self.table_porRealizarKWESTE.setObjectName("table_porRealizarKWESTE")
        self.table_porRealizarKWESTE.setColumnCount(0)
        self.table_porRealizarKWESTE.setRowCount(0)
        self.verticalLayout.addWidget(self.table_porRealizarKWESTE)
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.l_titulo_reportes_realizados = QtWidgets.QLabel(parent=self.widget_5)
        self.l_titulo_reportes_realizados.setMinimumSize(QtCore.QSize(0, 23))
        self.l_titulo_reportes_realizados.setMaximumSize(QtCore.QSize(16777215, 23))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.l_titulo_reportes_realizados.setFont(font)
        self.l_titulo_reportes_realizados.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.l_titulo_reportes_realizados.setObjectName("l_titulo_reportes_realizados")
        self.verticalLayout_2.addWidget(self.l_titulo_reportes_realizados)
        self.table_realizadoKWESTE = QtWidgets.QTableWidget(parent=self.widget_5)
        self.table_realizadoKWESTE.setObjectName("table_realizadoKWESTE")
        self.table_realizadoKWESTE.setColumnCount(0)
        self.table_realizadoKWESTE.setRowCount(0)
        self.verticalLayout_2.addWidget(self.table_realizadoKWESTE)
        self.horizontalLayout_2.addWidget(self.widget_5)
        self.gridLayout.addWidget(self.widget_2, 1, 0, 1, 3)
        self.l_logoKWESTE = QtWidgets.QLabel(parent=ContenedorGeneralKWESTE)
        self.l_logoKWESTE.setMinimumSize(QtCore.QSize(200, 40))
        self.l_logoKWESTE.setMaximumSize(QtCore.QSize(200, 40))
        self.l_logoKWESTE.setText("")
        self.l_logoKWESTE.setPixmap(QtGui.QPixmap("c:\\Users\\OEM\\Documents\\KENWORT_DEL_ESTE\\programakw\\App\\Front\\Source/LOGO_KWE.png"))
        self.l_logoKWESTE.setScaledContents(True)
        self.l_logoKWESTE.setObjectName("l_logoKWESTE")
        self.gridLayout.addWidget(self.l_logoKWESTE, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(parent=ContenedorGeneralKWESTE)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnMinimizar = QtWidgets.QPushButton(parent=self.widget)
        self.btnMinimizar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnMinimizar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\OEM\\Documents\\KENWORT_DEL_ESTE\\programakw\\App\\Front\\../../../../Documents/Business_Intelligence/Proyecto_BusinessIntelligence/App/Front/Source/Icon_Minimize.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnMinimizar.setIcon(icon)
        self.btnMinimizar.setIconSize(QtCore.QSize(30, 30))
        self.btnMinimizar.setObjectName("btnMinimizar")
        self.horizontalLayout.addWidget(self.btnMinimizar)
        self.btnCerrar = QtWidgets.QPushButton(parent=self.widget)
        self.btnCerrar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCerrar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\OEM\\Documents\\KENWORT_DEL_ESTE\\programakw\\App\\Front\\../../../../Documents/Business_Intelligence/Proyecto_BusinessIntelligence/App/Front/Source/Icon_Close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnCerrar.setIcon(icon1)
        self.btnCerrar.setIconSize(QtCore.QSize(30, 30))
        self.btnCerrar.setObjectName("btnCerrar")
        self.horizontalLayout.addWidget(self.btnCerrar)
        self.gridLayout.addWidget(self.widget, 0, 2, 1, 1)
        self.widget_3 = QtWidgets.QWidget(parent=ContenedorGeneralKWESTE)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_6 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_6.setMinimumSize(QtCore.QSize(550, 80))
        self.widget_6.setMaximumSize(QtCore.QSize(550, 80))
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnSubir = QtWidgets.QPushButton(parent=self.widget_6)
        self.btnSubir.setMinimumSize(QtCore.QSize(0, 30))
        self.btnSubir.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnSubir.setFont(font)
        self.btnSubir.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnSubir.setObjectName("btnSubir")
        self.horizontalLayout_6.addWidget(self.btnSubir)
        self.btnProcesar = QtWidgets.QPushButton(parent=self.widget_6)
        self.btnProcesar.setMinimumSize(QtCore.QSize(0, 30))
        self.btnProcesar.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnProcesar.setFont(font)
        self.btnProcesar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnProcesar.setObjectName("btnProcesar")
        self.horizontalLayout_6.addWidget(self.btnProcesar)
        self.btnEliminar = QtWidgets.QPushButton(parent=self.widget_6)
        self.btnEliminar.setMinimumSize(QtCore.QSize(0, 30))
        self.btnEliminar.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnEliminar.setFont(font)
        self.btnEliminar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnEliminar.setObjectName("btnEliminar")
        self.horizontalLayout_6.addWidget(self.btnEliminar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_Procesados = QtWidgets.QPushButton(parent=self.widget_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btn_Procesados.setFont(font)
        self.btn_Procesados.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_Procesados.setStyleSheet("#btn_Procesados{\n"
"background-color: rgb(132, 132, 132);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#btn_Procesados::hover{\n"
"background-color: rgb(218, 218, 218);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.btn_Procesados.setObjectName("btn_Procesados")
        self.horizontalLayout_7.addWidget(self.btn_Procesados)
        self.btn_Errores = QtWidgets.QPushButton(parent=self.widget_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btn_Errores.setFont(font)
        self.btn_Errores.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_Errores.setStyleSheet("#btn_Errores{\n"
"background-color: rgb(132, 132, 132);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#btn_Errores::hover{\n"
"background-color: rgb(218, 218, 218);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.btn_Errores.setObjectName("btn_Errores")
        self.horizontalLayout_7.addWidget(self.btn_Errores)
        self.btn_Originales = QtWidgets.QPushButton(parent=self.widget_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btn_Originales.setFont(font)
        self.btn_Originales.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_Originales.setStyleSheet("#btn_Originales{\n"
"background-color: rgb(132, 132, 132);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#btn_Originales::hover{\n"
"background-color: rgb(218, 218, 218);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.btn_Originales.setObjectName("btn_Originales")
        self.horizontalLayout_7.addWidget(self.btn_Originales)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5.addWidget(self.widget_6)
        self.widget_7 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_textoProgreso = QtWidgets.QLabel(parent=self.widget_7)
        self.label_textoProgreso.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_textoProgreso.setFont(font)
        self.label_textoProgreso.setText("")
        self.label_textoProgreso.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_textoProgreso.setObjectName("label_textoProgreso")
        self.horizontalLayout_4.addWidget(self.label_textoProgreso)
        self.btnAyuda = QtWidgets.QPushButton(parent=self.widget_7)
        self.btnAyuda.setMinimumSize(QtCore.QSize(45, 35))
        self.btnAyuda.setMaximumSize(QtCore.QSize(45, 35))
        self.btnAyuda.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnAyuda.setToolTipDuration(-1)
        self.btnAyuda.setStatusTip("")
        self.btnAyuda.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\OEM\\Documents\\KENWORT_DEL_ESTE\\programakw\\App\\Front\\Source/Icon_Help.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnAyuda.setIcon(icon2)
        self.btnAyuda.setIconSize(QtCore.QSize(30, 30))
        self.btnAyuda.setObjectName("btnAyuda")
        self.horizontalLayout_4.addWidget(self.btnAyuda)
        self.horizontalLayout_5.addWidget(self.widget_7)
        self.gridLayout.addWidget(self.widget_3, 2, 0, 1, 3)

        self.retranslateUi(ContenedorGeneralKWESTE)
        QtCore.QMetaObject.connectSlotsByName(ContenedorGeneralKWESTE)

    def retranslateUi(self, ContenedorGeneralKWESTE):
        _translate = QtCore.QCoreApplication.translate
        ContenedorGeneralKWESTE.setWindowTitle(_translate("ContenedorGeneralKWESTE", "KENWORTH DEL ESTE"))
        self.l_titulo_reportes_cola.setText(_translate("ContenedorGeneralKWESTE", "Reportes por hacer"))
        self.l_titulo_reportes_realizados.setText(_translate("ContenedorGeneralKWESTE", "Reportes Realizados"))
        self.btnMinimizar.setToolTip(_translate("ContenedorGeneralKWESTE", "Minimizar"))
        self.btnCerrar.setToolTip(_translate("ContenedorGeneralKWESTE", "Cerrar"))
        self.btnSubir.setToolTip(_translate("ContenedorGeneralKWESTE", "Seleccionar los archivos que se quieren procesar"))
        self.btnSubir.setText(_translate("ContenedorGeneralKWESTE", "Subir Archivo"))
        self.btnProcesar.setToolTip(_translate("ContenedorGeneralKWESTE", "Procesar"))
        self.btnProcesar.setText(_translate("ContenedorGeneralKWESTE", "Procesar"))
        self.btnEliminar.setToolTip(_translate("ContenedorGeneralKWESTE", "Eliminar todos los reportes que se han realizado."))
        self.btnEliminar.setText(_translate("ContenedorGeneralKWESTE", "Eliminar Procesados"))
        self.btn_Procesados.setText(_translate("ContenedorGeneralKWESTE", "Procesados"))
        self.btn_Errores.setText(_translate("ContenedorGeneralKWESTE", "Errores"))
        self.btn_Originales.setText(_translate("ContenedorGeneralKWESTE", "Originales"))
        self.btnAyuda.setToolTip(_translate("ContenedorGeneralKWESTE", "Ayuda"))
