# Form implementation generated from reading ui file 'c:\Users\OEM\Documents\KENWORT_DEL_ESTE\programakw\App\Front\KWRB.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VTrabajo(object):
    def setupUi(self, VTrabajo):
        VTrabajo.setObjectName("VTrabajo")
        VTrabajo.resize(950, 650)
        VTrabajo.setMinimumSize(QtCore.QSize(950, 650))
        VTrabajo.setMaximumSize(QtCore.QSize(950, 650))
        VTrabajo.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setUnderline(False)
        VTrabajo.setFont(font)
        VTrabajo.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        icon = QtGui.QIcon.fromTheme("KWRB")
        VTrabajo.setWindowIcon(icon)
        VTrabajo.setStyleSheet("#VTrabajo{\n"
"background-color: qconicalgradient(cx:0, cy:0, angle:114.5, stop:0.352273 rgba(0, 0, 0, 171), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:10px;\n"
"}\n"
"#btnCerrar{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"#btnMinimizar{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=VTrabajo)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_textoProgreso = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_textoProgreso.setEnabled(False)
        self.label_textoProgreso.setMinimumSize(QtCore.QSize(250, 0))
        self.label_textoProgreso.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_textoProgreso.setFont(font)
        self.label_textoProgreso.setText("")
        self.label_textoProgreso.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_textoProgreso.setObjectName("label_textoProgreso")
        self.gridLayout.addWidget(self.label_textoProgreso, 2, 2, 1, 1)
        self.btnAyuda = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAyuda.setMaximumSize(QtCore.QSize(16777213, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnAyuda.setFont(font)
        self.btnAyuda.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnAyuda.setAcceptDrops(False)
        self.btnAyuda.setToolTip("<html><head/><body><p align=\"justify\"><span style=\" font-size:12pt; font-weight:700;\">Solicita Ayuda</span></p></body></html>")
        self.btnAyuda.setToolTipDuration(0)
        self.btnAyuda.setStatusTip("")
        self.btnAyuda.setWhatsThis("")
        self.btnAyuda.setAccessibleName("")
        self.btnAyuda.setAccessibleDescription("")
        self.btnAyuda.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btnAyuda.setAutoFillBackground(False)
        self.btnAyuda.setStyleSheet("#btnAyuda{\n"
"    background-color: rgb(184, 184, 184);\n"
"    border-radius:5px;\n"
"}\n"
"#btnAyuda::hover{\n"
"    background-color: rgb(212, 202, 87);\n"
"}")
        self.btnAyuda.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.Nicaragua))
        self.btnAyuda.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\OEM\\Documents\\KENWORT_DEL_ESTE\\programakw\\App\\Front\\Source/Icon_Help.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnAyuda.setIcon(icon)
        self.btnAyuda.setIconSize(QtCore.QSize(32, 32))
        self.btnAyuda.setObjectName("btnAyuda")
        self.gridLayout.addWidget(self.btnAyuda, 2, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(200, 40))
        self.label_3.setStyleSheet("")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("c:\\Users\\OEM\\Documents\\KENWORT_DEL_ESTE\\programakw\\App\\Front\\Source/logo_kwrb.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.widget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_3.setMaximumSize(QtCore.QSize(100, 35))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnMinimizar = QtWidgets.QPushButton(parent=self.widget_3)
        self.btnMinimizar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnMinimizar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\OEM\\Documents\\KENWORT_DEL_ESTE\\programakw\\App\\Front\\Source/Icon_Minimize.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnMinimizar.setIcon(icon1)
        self.btnMinimizar.setIconSize(QtCore.QSize(30, 30))
        self.btnMinimizar.setObjectName("btnMinimizar")
        self.horizontalLayout_2.addWidget(self.btnMinimizar)
        self.btnCerrar = QtWidgets.QPushButton(parent=self.widget_3)
        self.btnCerrar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCerrar.setMouseTracking(False)
        self.btnCerrar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\OEM\\Documents\\KENWORT_DEL_ESTE\\programakw\\App\\Front\\Source/Icon_Close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnCerrar.setIcon(icon2)
        self.btnCerrar.setIconSize(QtCore.QSize(30, 30))
        self.btnCerrar.setObjectName("btnCerrar")
        self.horizontalLayout_2.addWidget(self.btnCerrar)
        self.gridLayout.addWidget(self.widget_3, 0, 4, 1, 1)
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(550, 70))
        self.widget_2.setMaximumSize(QtCore.QSize(550, 70))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnSubir = QtWidgets.QPushButton(parent=self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnSubir.setFont(font)
        self.btnSubir.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnSubir.setStyleSheet("#btnSubir{\n"
"background-color: qlineargradient(spread:pad, x1:0.113227, y1:0.426, x2:0, y2:0, stop:0 rgba(0, 255, 0, 153), stop:1 rgba(0, 0, 0, 63));\n"
"border-radius:12px;\n"
"}\n"
"#btnSubir::Hover{\n"
"background-color: rgb(46, 212, 60);\n"
"}")
        self.btnSubir.setObjectName("btnSubir")
        self.horizontalLayout_4.addWidget(self.btnSubir)
        self.btnComenzar = QtWidgets.QPushButton(parent=self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnComenzar.setFont(font)
        self.btnComenzar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnComenzar.setStyleSheet("#btnComenzar{\n"
"background-color: qlineargradient(spread:pad, x1:0.17, y1:0.7385, x2:0, y2:0, stop:0.431818 rgba(0, 245, 255, 142), stop:1 rgba(0, 0, 0, 97));\n"
"border-radius:12px;\n"
"}\n"
"#btnComenzar::Hover{\n"
"background-color: rgb(79, 188, 204);\n"
"}")
        self.btnComenzar.setObjectName("btnComenzar")
        self.horizontalLayout_4.addWidget(self.btnComenzar)
        self.btnEliminar = QtWidgets.QPushButton(parent=self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnEliminar.setFont(font)
        self.btnEliminar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnEliminar.setStyleSheet("#btnEliminar{\n"
"background-color: qlineargradient(spread:pad, x1:0.113227, y1:0.426, x2:0, y2:0, stop:0 rgba(255, 0, 0, 153), stop:1 rgba(0, 0, 0, 63));\n"
"border-radius:12px;\n"
"}\n"
"#btnEliminar::Hover{\n"
"background-color: rgb(193, 15, 15);\n"
"}")
        self.btnEliminar.setObjectName("btnEliminar")
        self.horizontalLayout_4.addWidget(self.btnEliminar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_Procesados = QtWidgets.QPushButton(parent=self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_Procesados.setFont(font)
        self.btn_Procesados.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_Procesados.setStyleSheet("#btn_Procesados{\n"
"background-color: rgb(132, 132, 132);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#btn_Procesados::hover{\n"
"background-color: rgb(218, 218, 218);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.btn_Procesados.setObjectName("btn_Procesados")
        self.horizontalLayout_5.addWidget(self.btn_Procesados)
        self.btn_Errores = QtWidgets.QPushButton(parent=self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_Errores.setFont(font)
        self.btn_Errores.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_Errores.setStyleSheet("#btn_Errores{\n"
"background-color: rgb(132, 132, 132);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#btn_Errores::hover{\n"
"background-color: rgb(218, 218, 218);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.btn_Errores.setObjectName("btn_Errores")
        self.horizontalLayout_5.addWidget(self.btn_Errores)
        self.btn_Originales = QtWidgets.QPushButton(parent=self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_Originales.setFont(font)
        self.btn_Originales.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_Originales.setStyleSheet("#btn_Originales{\n"
"background-color: rgb(132, 132, 132);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#btn_Originales::hover{\n"
"background-color: rgb(218, 218, 218);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.btn_Originales.setObjectName("btn_Originales")
        self.horizontalLayout_5.addWidget(self.btn_Originales)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.gridLayout.addWidget(self.widget_2, 2, 0, 1, 1)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_4 = QtWidgets.QWidget(parent=self.widget)
        self.widget_4.setMinimumSize(QtCore.QSize(475, 0))
        self.widget_4.setMaximumSize(QtCore.QSize(475, 16777215))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget_4)
        self.label.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label.setSizeIncrement(QtCore.QSize(0, 23))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listaTrabajo = QtWidgets.QListWidget(parent=self.widget_4)
        self.listaTrabajo.setMinimumSize(QtCore.QSize(430, 0))
        self.listaTrabajo.setMaximumSize(QtCore.QSize(430, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.listaTrabajo.setFont(font)
        self.listaTrabajo.setStyleSheet("#listaTrabajo{\n"
"padding-top: 10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    border-radius:15px;\n"
"}\n"
"#listaTrabajo::item { padding-right: 10px; }")
        self.listaTrabajo.setDragEnabled(True)
        self.listaTrabajo.setDragDropOverwriteMode(True)
        self.listaTrabajo.setDragDropMode(QtWidgets.QAbstractItemView.DragDropMode.DragDrop)
        self.listaTrabajo.setDefaultDropAction(QtCore.Qt.DropAction.MoveAction)
        self.listaTrabajo.setViewMode(QtWidgets.QListView.ViewMode.ListMode)
        self.listaTrabajo.setObjectName("listaTrabajo")
        self.verticalLayout.addWidget(self.listaTrabajo)
        self.horizontalLayout_3.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(parent=self.widget)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_5)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label_2.setSizeIncrement(QtCore.QSize(0, 23))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.listaRealizado = QtWidgets.QListWidget(parent=self.widget_5)
        self.listaRealizado.setMinimumSize(QtCore.QSize(430, 0))
        self.listaRealizado.setMaximumSize(QtCore.QSize(430, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.listaRealizado.setFont(font)
        self.listaRealizado.setStyleSheet("#listaRealizado{\n"
"padding-top: 10px;\n"
"    background-color: rgb(193, 193, 193);\n"
"    border-radius:15px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"#listaRealizado::item { padding-right: 10px; }")
        self.listaRealizado.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.listaRealizado.setLineWidth(1)
        self.listaRealizado.setMovement(QtWidgets.QListView.Movement.Static)
        self.listaRealizado.setObjectName("listaRealizado")
        self.verticalLayout_2.addWidget(self.listaRealizado)
        self.horizontalLayout_3.addWidget(self.widget_5)
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 3, 1, 1)
        self.label_3.raise_()
        self.widget.raise_()
        self.btnAyuda.raise_()
        self.widget_2.raise_()
        self.widget_3.raise_()
        self.label_textoProgreso.raise_()
        VTrabajo.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=VTrabajo)
        self.statusbar.setObjectName("statusbar")
        VTrabajo.setStatusBar(self.statusbar)

        self.retranslateUi(VTrabajo)
        QtCore.QMetaObject.connectSlotsByName(VTrabajo)

    def retranslateUi(self, VTrabajo):
        _translate = QtCore.QCoreApplication.translate
        VTrabajo.setWindowTitle(_translate("VTrabajo", "RIO BRAVO"))
        self.btnMinimizar.setToolTip(_translate("VTrabajo", "Minimizar"))
        self.btnCerrar.setToolTip(_translate("VTrabajo", "Cerrar"))
        self.btnSubir.setText(_translate("VTrabajo", "Subir"))
        self.btnComenzar.setText(_translate("VTrabajo", "Comenzar"))
        self.btnEliminar.setText(_translate("VTrabajo", "Eliminar"))
        self.btn_Procesados.setText(_translate("VTrabajo", "Procesados"))
        self.btn_Errores.setText(_translate("VTrabajo", "Erroneos"))
        self.btn_Originales.setText(_translate("VTrabajo", "Originales"))
        self.label.setText(_translate("VTrabajo", "Reportes en Cola"))
        self.listaTrabajo.setSortingEnabled(True)
        self.label_2.setText(_translate("VTrabajo", "Reportes Realizados"))
